shortener/urls.py
from django.conf.urls import patterns, include, url
 
urlpatterns = patterns('shortener.views',
    url(r'^$', 'index', name='home'),
    # for our home/index page
 
    url(r'^redirect/$', 'redirect_original', name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
 
    url(r'^makeshort/$', 'shorten_url', name='shortenurl'),
    # this will create a URL's short id and return the short URL
    )

urlshortener/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('shortener.urls',namespace='shortener')),
]

shortener/models.py
from django.db import models
class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)
 
def __str__(self):
    return self.httpurl
# Create your models here.

shortener/views.py
# Create your views here.
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from shortener.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.context_processors import csrf
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from shortener.models import Urls
from shortener.serializers import UrlSerializer
 
def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('shortener/index.html', c)
 
def redirect_original(request):
    # url = get_object_or_404(Urls, pk=short_id) # get object, if not  found return 404 error
    # url.count += 1
    # url.save()
    # return HttpResponseRedirect(url.httpurl)  
    #import pdb; pdb.set_trace()  
    short_url = request.POST.get('short_url')
    short_id = short_url.replace(settings.SITE_URL+'/','')
    url_entry_in_db = Urls.objects.filter(short_id = short_id)
    return HttpResponseRedirect(url_entry_in_db[0].httpurl)

@api_view(['GET', 'POST'])
def shorten_url(request):
    #import pdb;pdb.set_trace()
    if request.method == 'GET':
        pass

    elif request.method == 'POST':
        url = request.POST.get("url", '')
        response_data = {}
        # import pdb;pdb.set_trace()
        url_entry_in_db = Urls.objects.filter(httpurl=url)
        if url_entry_in_db:
            response_data['url'] = settings.SITE_URL+"/"+ url_entry_in_db[0].short_id
            return HttpResponse(json.dumps(response_data),  content_type="application/json")
        short_id = get_short_code()
        data ={'httpurl':url,'short_id':short_id}
        serializer=UrlSerializer(data = data)
        if serializer.is_valid():
            serializer.save()
            response_data['url'] = settings.SITE_URL + "/" + short_id
            return HttpResponse(json.dumps(response_data),  content_type="application/json")

        else:
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST)





'''
    url = request.POST.get("url", '')
    if not (url == ''):
        response_data = {}
        url_entry_in_db = Urls.objects.filter(httpurl=url)
        if url_entry_in_db:
            response_data['url'] = settings.SITE_URL+"/"+ url_entry_in_db[0].short_id
            return HttpResponse(json.dumps(response_data),  content_type="application/json")
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id)
        b.save()
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")
'''
 
def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        if not Urls.objects.filter(pk=short_id):
            return short_id
        else:
            pass

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html>
	<head>
 		<title>{% block title %}Welcome to mysite{% endblock %}</title>
 		{% load staticfiles %}
	 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	 	<link rel="stylesheet" type="text/css" href="{% static 'shortener/css/custom.css' %}" />
	 	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<script type="text/javascript">
	 	$(function() {
	 		$('#submitButton').click(function() {
		 		$.ajax({
					 type: "POST",
					 url: "/makeshort/",
					 data: {
					 'url' : $('#url').val(),
					 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
		 			},
				 success: returnSuccess,
				 dataType: 'json'
				 });
	 		});
		});
	  
		function returnSuccess(data, textStatus, jqXHR) {
		 if(data.url) {
		 	$('#url-result').text(data.url);
		 		$('#url').val("");
		 		} else {
		 		$('#url-result').text("Do not submit blank."); 
		 }
		   
	}
	</script>
	<body>
		<div id="wrap">
			<header>
	 			<h1><a href="{% url 'shortener:home' %}">URL Shortner</a><small>Shorten the URL</small></h1>
			</header>
  
			<div id="content">
				{% block content %}
  
				{% endblock %}
			</div>
		</div>
	</body>
</html>

shortener/templates/shortener/index.html
{% extends "shortener/base.html" %}
  
{% block title %}URL Shortner - Make your URL shorter!{% endblock %}
  
{% block content %}
  
<div class="panel panel-default">
 <div class="panel-body">
 <div class="col-sm-9">
 <input type="text" name="url" id="url" class="form-control input-sm" placeholder="Enter the url to shorten" />
 </div>
 <div class="col-sm-3">
 {% csrf_token %}
 <button id="submitButton" class="btn btn-primary">Submit</button></p> 
 </div>
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>
{% endblock %}